trigger:
- main

resources:
  repositories:
  - repository: FoodTourServerGitHub   
    type: github
    name: coderscool/FoodTourServer
    endpoint: FoodTour-Github  

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'foodtourserveracr'
  imageRepository: 'coderscoolfoodtourserver'
  containerRegistry: 'foodtourserveracr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'foodtourserveracr6661450a-auth'
  chartPath: 'K8s'
  aksServiceConnection: 'foodtourserver-aks-default'

  # Agent VM image name
pool:
  name: 'FoodTourPool'


stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: Build
    pool:
      name: 'FoodTourPool'
    steps:
    - checkout: FoodTourServerGitHub   
      persistCredentials: true
    # Build & push web-api
    - task: Docker@2
      displayName: Build and Push web-api
      inputs:
        command: buildAndPush
        repository: web-api
        dockerfile: WebApplication1/Dockerfile
        buildContext: .
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'FoodTourServer'
    pool:
      name: 'FoodTourPool'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true
          - script: |
              sudo apt-get update
              sudo apt-get install -y unzip
            displayName: 'Install unzip'
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          
          - task: KubectlInstaller@0
            inputs:
              kubernetesVersion: 'latest'
            displayName: 'Install kubectl'

          - task: HelmDeploy@0
            displayName: Helm upgrade/install
            inputs:
              connectionType: 'Azure Resource Manager'
              kubernetesServiceConnection: $(aksServiceConnection)
              azureResourceGroup: 'foodtourservice-rg'
              kubernetesCluster: 'foodtourservice-aks'
              command: upgrade
              chartType: FilePath
              chartPath: $(chartPath)
              releaseName: foodtourserver
              install: true
              arguments: >
                --set web-api.image=$(containerRegistry)/web-api:$(Build.BuildId)