trigger:
- main

resources:
  repositories:
  - repository: FoodTourServerGitHub   
    type: github
    name: coderscool/FoodTourServer
    endpoint: FoodTour-Github  

parameters:
  - name: services
    type: object
    default:
      - name: web-api
        dockerfile: WebApplication1/Dockerfile
      - name: identity-commnad
        dockerfile: Services/Identity/Command/WorkerService1/Dockerfile
      - name: identity-query
        dockerfile: Services/Identity/Query/GrpcService1/Dockerfile

variables:
  # Container registry service connection
  dockerRegistryServiceConnection: 'foodtourserveracr'
  imageRepository: 'coderscoolfoodtourserver'
  containerRegistry: 'foodtourserveracr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'foodtourserveracr6661450a-auth'
  chartPath: 'K8s'
  aksServiceConnection: 'foodtourserver-aks-default'

pool:
  name: 'FoodTourPool'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: Build
    pool:
      name: 'FoodTourPool'
    steps:
    - checkout: FoodTourServerGitHub   
      persistCredentials: true
    - ${{ each service in parameters.services }}:
      - task: Docker@2
        displayName: Build and Push ${{ service.name }}
        inputs:
          command: buildAndPush
          repository: ${{ service.name }}
          dockerfile: ${{ service.dockerfile }}
          buildContext: $(Build.SourcesDirectory)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'FoodTourServer'
    pool:
      name: 'FoodTourPool'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'foodtour-prod-conn'
              azureResourceGroup: 'foodtourserver-rg'
              kubernetesCluster: 'foodtourserver-aks'
              command: get
              arguments: pods -n default

          - task: HelmDeploy@0
            displayName: Helm upgrade/install
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(aksServiceConnection)
              azureResourceGroup: 'foodtourserver-rg'
              kubernetesCluster: 'foodtourserver-aks'
              namespace: default
              command: upgrade
              chartType: FilePath
              chartPath: $(chartPath)
              releaseName: foodtourserver
              install: true
              arguments: >
                --set webapi.image=$(containerRegistry)/web-api:$(Build.BuildId)
                --set identitycommand.image=$(containerRegistry)/identity-command:$(Build.BuildId)
                --set identityquery.image=$(containerRegistry)/identity-query:$(Build.BuildId)
                --timeout 5m

          