trigger:
- main

resources:
  repositories:
  - repository: FoodTourServerGitHub   
    type: github
    name: coderscool/FoodTourServer
    endpoint: FoodTour-Github  

variables:
  dockerRegistryServiceConnection: 'foodtourserveracr'
  containerRegistry: 'foodtourserveracr.azurecr.io'
  tag: '$(Build.BuildId)'
  chartPath: 'K8s'
  aksServiceConnection: 'foodtourserver-aks-default'

pool:
  name: 'FoodTourPool'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: Build
    steps:
    - checkout: FoodTourServerGitHub   
      persistCredentials: true

    - script: |
        echo "Logging into ACR..."
        az acr login --name foodtourserveracr
        docker buildx create --use
        docker buildx build -t $(containerRegistry)/web-api:$(Build.BuildId) -f WebApplication1 --push .
      displayName: Build and Push web-api with buildx

    - script: |
        docker buildx build -t $(containerRegistry)/identity-command:$(Build.BuildId) -f Services/Identity/Command/WorkerService1 --push .
      displayName: Build and Push identity-command with buildx

    - script: |
        docker buildx build -t $(containerRegistry)/identity-query:$(Build.BuildId) -f Services/Identity/Query/GrpcService1 --push .
      displayName: Build and Push identity-query with buildx

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'FoodTourServer'
    pool:
      name: 'FoodTourPool'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: Helm upgrade/install
            inputs:
              connectionType: 'Azure Resource Manager'
              kubernetesServiceConnection: $(aksServiceConnection)
              azureResourceGroup: 'foodtourservice-rg'
              kubernetesCluster: 'foodtourservice-aks'
              command: upgrade
              chartType: FilePath
              chartPath: $(chartPath)
              releaseName: foodtourserver
              install: true
              arguments: >
                --set web-api.image=$(containerRegistry)/web-api:$(Build.BuildId)
                --set identity-command.image=$(containerRegistry)/identity-command:$(Build.BuildId)
                --set identity-query.image=$(containerRegistry)/identity-query:$(Build.BuildId)


