domain: api.foodtourserver.com

webapi:
  image: foodtourserveracr.azurecr.io/web-api:latest
  port: 8080
  env:
    - name: IdentityQuery__Url
      value: "http://identity-query-service:5123"

identitycommand:
  image: foodtourserveracr.azurecr.io/identity-command:latest

identityquery:
  image: foodtourserveracr.azurecr.io/identity-query:latest
  port: 5123

