apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-query-deployment
  annotations:
    azure.workload.identity/client-id: 35a020fe-9513-4139-9087-e2385cd5cb45
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-query
  template:
    metadata:
      labels:
        app: account-query
    spec:
      containers:
        - name: account-query
          image: {{ .Values.accountquery.image }}
          ports:
            - containerPort: {{ .Values.accountquery.port }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"