apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodtourserver-ingress
  annotations:
    ingressClassName: nginx
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /web-api
            pathType: Prefix
            backend:
              service:
                name: web-api-service
                port:
                  number: 80