apiVersion: v1
kind: Service
metadata:
  name: statistic-query-service
spec:
  type: ClusterIP
  selector:
    app: statistic-query
  ports:
    - port: 8080
      targetPort: {{ .Values.statisticquery.port }}